services:
  postgres:
    image: postgres:17.6
    container_name: my_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8.2.1
    container_name: my_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-rest:
    image: ghcr.io/hiett/serverless-redis-http:1.8.0
    container_name: my_redis_rest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${UPSTASH_REDIS_REST_TOKEN:-dev-token}
      SRH_CONNECTION_STRING: redis://redis:6379
      SRH_PORT: ${UPSTASH_REDIS_REST_PORT:-8079}
    ports:
      - "${UPSTASH_REDIS_REST_PORT:-8079}:${UPSTASH_REDIS_REST_PORT:-8079}"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
